### ISSUE TITLE
Dynamic DNS update support

### ISSUE THREAD

**Issue by nuxi** [nuxi/acme-tiny#3]
Supporting DDNS would make is simpler to update the DNS records and allow the tool to be properly automated in cron like the original http-01 version is.

**Comment by bugness-chl** [comment]
Hi,
@Daniel-Abrecht added it via a pull request on my copy : https://github.com/bugness-chl/acme-tiny-dns01/pull/1 / Daniel-Abrecht/acme-tiny-dns01@34c0f341f00c529891b7a3fd425c023053a246d1
Sorry, I haven't yet updated the doc.

**Comment by nuxi** [comment]
Yeah, I think I'll just pull yours in entirely and use it as the base for ACMEv2 work.

**Comment by nuxi** [comment]
I ended up getting ACMEv2 by pulling in diafygi's new code and re-applying the http-01 => dns-01 patch.
